name: Deploy Aplikasi 1 (Port 2000)

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode sumber
        uses: actions/checkout@v3

      - name: Konfigurasi SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy ke Direktori Web 1
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          # Menyalin kode ke direktori Aplikasi 1 (Port 2000)
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ ${SERVER_USER}@${SERVER_IP}:/var/www/web1.com/public_html/

          # Restart PHP-FPM untuk memuat ulang kode
          ssh ${SERVER_USER}@${SERVER_IP} "sudo systemctl restart php8.1-fpm"
